[package]
name = "optix_sys"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cust_raw = { version = "0.11.2", path = "../cust_raw" }

[build-dependencies]
cc = "1.0.71"
find_cuda_helper = { version = "0.1", path = "../find_cuda_helper" }
