[package]
name = "device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuda_std = { version = "0.1", path = "../../../../cuda_std" }

[lib]
crate-type = ["cdylib"]

