[package]
name = "add"
version = "0.1.0"
edition = "2021"

[dependencies]
cust = { version = "0.1", path = "../../../../crates/cust" }
nanorand = "0.6.1"

[build-dependencies]
cuda_builder = { version = "0.1", path = "../../../../crates/cuda_builder" }
