[package]
name = "denoiser"
version = "0.1.0"
edition = "2021"

[dependencies]
optix = { version = "0.1", path = "../../../crates/optix" }
structopt = "0.3"
cust = { version = "0.1", path = "../../../crates/cust", features = ["vek"] }
image = "0.23.14"
